# Generated by Django 5.1.5 on 2025-02-07 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_duration', models.CharField(max_length=30)),
                ('course_name', models.CharField(max_length=30)),
                ('fees', models.CharField(max_length=30)),
                ('course_descriptions', models.TextField()),
                ('course_lecture_flow', models.FileField(upload_to='media/lectureflow/')),
                ('course_heandbook', models.FileField(upload_to='media/heandbook/')),
                ('course_interview_qustion', models.FileField(upload_to='media/interviewpreperation/')),
                ('course_assignment', models.FileField(upload_to='media/assignment/')),
                ('course_tutor_name', models.CharField(max_length=30)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
