# Generated by Django 5.1.5 on 2025-02-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_pic',
            field=models.FileField(default='media/category.png', upload_to='media/images/'),
        ),
    ]
