# Generated by Django 5.1.5 on 2025-02-10 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_course_course_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_logo', models.FileField(default='media/company', upload_to='media/image/')),
                ('company_descriptions', models.TextField()),
                ('company_email', models.CharField(max_length=20)),
                ('company_phone_no', models.CharField(max_length=11)),
                ('company_website', models.CharField(max_length=50)),
                ('company_address', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
