# Generated by Django 5.1.5 on 2025-02-17 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='enrollcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='PENDING', max_length=30)),
                ('fees_status', models.CharField(max_length=30)),
                ('paid_fees', models.IntegerField(default=0)),
                ('cour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('learner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.learners')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
